CREATE DATABASE ERP
GO

USE ERP
GO

CREATE TABLE TBL_DEPARTMENT(
	DEPT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,DEPT_NAME VARCHAR(100) NOT NULL
	,DEPT_DESC VARCHAR(100) NOT NULL
)

GO

CREATE TABLE TBL_PAY_GRADE(
	PAY_GRADE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,PAY_GRADE_NAME VARCHAR(100) NOT NULL
	,PAY_GRADE_MINIMUM FLOAT NOT NULL
	,PAY_GRADE_MAXIMUM FLOAT NOT NULL
)

GO

CREATE TABLE TBL_SALARY_TYPE(
	SALARY_TYPE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,SALARY_TYPE_NAME VARCHAR(100) NOT NULL
	,SALARY_TYPE_CODE VARCHAR(50) NOT NULL
	,UNITS_PER_YEAR INT NOT NULL
)

GO

CREATE TABLE TBL_COMPENSATION_TYPE(
	COMP_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY
	,COMP_TYPE_NAME NVARCHAR(100) NOT NULL
	,COMP_TYPE_DESC NVARCHAR(MAX) NOT NULL
	,COMP_TYPE_VALUE FLOAT NOT NULL
)

GO

CREATE TABLE TBL_EMPLOYEE(
	EMP_ID INT IDENTITY PRIMARY KEY
	,EMP_NUMBER AS (CONVERT(VARCHAR,YEAR(EMP_HIRE_DATE))+'-'+REPLICATE('0',5-LEN(EMP_ID))
	+CAST(EMP_ID AS VARCHAR))+'-'+LEFT(EMP_FIRST_NAME,1)+LEFT(EMP_LAST_NAME,1)
	,EMP_FIRST_NAME VARCHAR(100) NOT NULL
	,EMP_MIDDLE_NAME VARCHAR(100) NULL
	,EMP_LAST_NAME VARCHAR(100) NOT NULL
	,EMP_HIRE_DATE DATE NOT NULL
	,EMP_STATUS VARCHAR(100) NOT NULL
)

CREATE TABLE TBL_EMPLOYEE_INFO(
	EMP_INFO_ID INT IDENTITY(1,1) PRIMARY KEY
	,EMP_ID INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,GENDER VARCHAR(6) NOT NULL CHECK(GENDER IN ('MALE','FEMALE'))
	,BIRTHPLACE NVARCHAR(100) NOT NULL
	,CONTACT_NO NUMERIC NOT NULL
	,EMAIL_ADD NVARCHAR(100) NOT NULL
	,GSIS_NO NVARCHAR(100) NOT NULL
	,PAGIBIG_NO NVARCHAR(100) NOT NULL
	,PHILHEALTH_NO NVARCHAR(100) NOT NULL
	,SSS_NO NVARCHAR(100) NOT NULL
	,TIN_NO NVARCHAR(100) NOT NULL
	,AGENCY_EMP_NO NVARCHAR(100) NOT NULL
)

ALTER TABLE TBL_EMPLOYEE_INFO ADD BIRTHDATE DATE NOT NULL

GO

CREATE TABLE EMP_RATING_VAL(
	EMP_RATING_ID INT IDENTITY(1,1) PRIMARY KEY
	,RATING_NAME NVARCHAR(100) NOT NULL
	,RATING_DESC NVARCHAR(100) NOT NULL
	,RATING_VAL DECIMAL NOT NULL
)

GO

CREATE TABLE TBL_JOB(
	JOB_ID INT IDENTITY(1,1) PRIMARY KEY
	,JOB_NAME VARCHAR(100) NOT NULL
	,DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_DEPARTMENT(DEPT_ID)
	,PAY_GRADE_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_PAY_GRADE(PAY_GRADE_ID)
	,SALARY_TYPE_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_SALARY_TYPE(SALARY_TYPE_ID)
)

GO

CREATE TABLE TBL_APPLICANT(
	APPLICANT_ID INT IDENTITY PRIMARY KEY
	,APPLICANT_NUMBER AS CONVERT(VARCHAR,YEAR(APPLICANT_CREATION_DATE))+'-'+REPLICATE('0',
		5-LEN(APPLICANT_ID))+CAST(APPLICANT_ID AS VARCHAR)
	,APPLICANT_CREATION_DATE DATE NOT NULL
	,APPLICANT_PASSWORD VARCHAR(100) NOT NULL
	,APPLICANT_FIRST_NAME VARCHAR(100) NOT NULL
	,APPLICANT_MIDDLE_NAME VARCHAR(100) NOT NULL
	,APPLICANT_LAST_NAME VARCHAR(100) NOT NULL
	,APPLICANT_EMAIL VARCHAR(100) NOT NULL
	,APPLICANT_STATUS VARCHAR(50) NOT NULL
)

GO

CREATE TABLE TBL_APPLICANT_INFO(
	APPLICANT_INFO_ID INT IDENTITY(1,1) PRIMARY KEY
	,APPLICANT_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_APPLICANT(APPLICANT_ID)
	,GENDER VARCHAR(6) NOT NULL CHECK(GENDER IN ('MALE','FEMALE'))
	,BIRTHPLACE NVARCHAR(100) NOT NULL
	,CONTACT_NO INT NOT NULL
	,EMAIL_ADD NVARCHAR(100) NOT NULL
	,GSIS_NO NVARCHAR(100) NOT NULL
	,PAGIBIG_NO NVARCHAR(100) NOT NULL
	,PHILHEALTH_NO NVARCHAR(100) NOT NULL
	,SSS_NO NVARCHAR(100) NOT NULL
	,TIN_NO NVARCHAR(100) NOT NULL
	,AGENCY_EMP_NO NVARCHAR(100) NOT NULL
)

GO

CREATE TABLE TBL_REQUIREMENT(
	REQ_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,REQ_NAME VARCHAR(100) NOT NULL
)

GO

CREATE TABLE TBL_REQUIREMENT_SET(
	REQ_SET_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,REQ_SET_NAME VARCHAR(100) NOT NULL
)

GO

CREATE TABLE REF_REQUIREMENT_SET(
	REQ_SET_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_REQUIREMENT_SET(REQ_SET_ID)
	,REQ_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_REQUIREMENT(REQ_ID)
)

GO

CREATE TABLE TBL_JOB_POST(
	JOB_POST_ID INT IDENTITY(1,1) PRIMARY KEY
	,JOB_POST_NAME VARCHAR(100) NOT NULL
	,JOB_POST_DESCRIPTION VARCHAR(MAX) NOT NULL
	,REQUIREMENT_SET_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_REQUIREMENT_SET(REQ_SET_ID)
	,JOB_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_JOB(JOB_ID)
	,JOB_POST_CREATOR INT NOT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,JOB_POST_DATE DATE NOT NULL
)

GO

CREATE TABLE REF_JOB_APPLICANT(
	JOB_POST_ID INT FOREIGN KEY REFERENCES TBL_JOB_POST(JOB_POST_ID)
	,APPLICANT_ID INT FOREIGN KEY REFERENCES TBL_APPLICANT(APPLICANT_ID)
)

GO

--CREATE TABLE REF_DEPARTMENT_EMPLOYEE(
--	DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_DEPARTMENT(DEPT_ID)
--	,EMP_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
--)

--GO

CREATE TABLE REF_DEPARTMENT_MANAGER(
	DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_DEPARTMENT(DEPT_ID)
	,MANAGER_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
)

GO

CREATE TABLE TBL_EXAMINATION(
	EXAM_ID INT IDENTITY(1,1) PRIMARY KEY
	,EXAM_NAME VARCHAR(100) NOT NULL
	,EXAMINER INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,EXAM_DATE DATE NOT NULL
	,EXAM_PASSING_SCORE INT NOT NULL
)

GO

CREATE TABLE TBL_APPLICANT_EVALUATION(
	APPLICANT_EVALUATION_ID INT IDENTITY(1,1) PRIMARY KEY
	,APPLICANT_ID INT FOREIGN KEY REFERENCES TBL_APPLICANT(APPLICANT_ID)
	,APPLICANT_EVALUATION_RESULT VARCHAR(MAX) NULL
)

GO

CREATE TABLE TBL_INTERVIEW(
	INTERVIEW_ID INT IDENTITY(1,1) PRIMARY KEY
	,INTERVIEW_NAME VARCHAR(100) NOT NULL
	,INTERVIEWER INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,INTERVIEW_SCHEDULE_DATE_TIME DATETIME NOT NULL
	,INTERVIEWEE_DATE_ARRIVED DATE NULL
	,INTERVIEW_REMARKS VARCHAR(MAX) NULL
	,EVALUATION_ID INT FOREIGN KEY REFERENCES TBL_APPLICANT_EVALUATION(APPLICANT_EVALUATION_ID)
)

GO

CREATE TABLE REF_APPLICANT_EXAMINATION(
	EXAM_ID INT FOREIGN KEY REFERENCES TBL_EXAMINATION(EXAM_ID)
	,EXAM_SCORE INT NULL
	,EVALUATION_ID INT FOREIGN KEY REFERENCES TBL_APPLICANT_EVALUATION(APPLICANT_EVALUATION_ID)
)

GO

CREATE TABLE TBL_PERFORMANCE_EVALUATION(
	PE_ID INT IDENTITY(1,1) PRIMARY KEY
	,PE_NAME VARCHAR(100) NOT NULL
	,PE_DATE DATE NULL
	,EVALUATOR INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,EMPLOYEE INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,RATING FLOAT NULL
	,REMARKS VARCHAR(MAX) NULL
)

GO

CREATE TABLE REF_EMPLOYEE_JOB(
	EMP_ID INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,JOB_ID INT FOREIGN KEY REFERENCES TBL_JOB(JOB_ID)
	,START_DATE DATE NOT NULL
	,END_DATE DATE NULL
)

GO

CREATE TABLE TBL_COMPETENCY_CLUSTER(
	COMPETENCY_CLUSTER_ID INT IDENTITY(1,1) PRIMARY KEY
	,COMPETENCY_CLUSTER_NAME NVARCHAR(100) NOT NULL
)

GO

CREATE TABLE TBL_COMPETENCY(
	COMPETENCY_ID INT IDENTITY(1,1) PRIMARY KEY
	,COMPETENCY_NAME NVARCHAR(100) NOT NULL
	,COMPETENCY_CLUSTER_ID INT NOT NULL FOREIGN KEY REFERENCES 
		TBL_COMPETENCY_CLUSTER(COMPETENCY_CLUSTER_ID)
)

GO

CREATE TABLE TBL_COMPETENCY_STATUS(
	COMPENTENCY_STATUS_ID INT IDENTITY(1,1) PRIMARY KEY
	,COMPETENCY_STATUS_EMP_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,COMPETENCY_STATUS_COMPETENCY_SCORE DECIMAL NULL
	,COMPETENCY_STATUS_TIME_STAMP DATETIME NULL
)

GO

CREATE TABLE TBL_JOB_COMPETENCY(
	JOB_COMPETENCY_ID INT IDENTITY(1,1) PRIMARY KEY
	,JOB_COMPETENCY_JOB_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_JOB(JOB_ID)
	,JOB_COMPETENCY_COMPETENCY_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_COMPETENCY(COMPETENCY_ID)
	,JOB_COMPETENCY_COMPETENCY_LEVEL NVARCHAR(50) NULL DEFAULT ('BASIC')
)

GO

CREATE TABLE TBL_TRAINING(
	TRAINING_ID INT IDENTITY(1,1) PRIMARY KEY
	,TRAINING_NAME NVARCHAR(100) NOT NULL
)

GO

CREATE TABLE TBL_TRAINING_COMPETENCY(
	TRAINING_COMPETENCY_ID INT IDENTITY(1,1) PRIMARY KEY
	,TRAINING_COMPETENCY_TRAINING_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_TRAINING(TRAINING_ID)
	,TRAINING_COMPETENCY_COMPETENCY_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_COMPETENCY(COMPETENCY_ID)
	,TRAINING_COMPETENCY_COMPETENCY_LEVEL NVARCHAR(50) DEFAULT ('BASIC')
)

GO

CREATE TABLE TBL_COURSE_CATEGORY(
	COURSE_CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY
	,COURSE_CATEGORY_NAME NVARCHAR(500) NOT NULL
)

GO

CREATE TABLE TBL_COURSE(
	COURSE_ID INT IDENTITY(1,1) PRIMARY KEY
	,COURSE_NAME NVARCHAR(500) NOT NULL
	,COURSE_DESCRIPTION NVARCHAR(500) NOT NULL
	,COURSE_LEARNING_FILE VARBINARY(MAX) NOT NULL
	,COURSE_CATEGORY_ID INT NOT NULL FOREIGN KEY REFERENCES TBL_COURSE_CATEGORY(COURSE_CATEGORY_ID)
)

GO

CREATE TABLE TBL_EMPLOYEE_COURSE_ENROLMENT(
	EMP_C_E_ID INT IDENTITY(1,1) PRIMARY KEY
	,EMP_C_E_DATEOFENROLMENT DATETIME NOT NULL
	,EMP_C_E_DATEOFCOMPLETION DATETIME NULL
	,EMP_C_E_COURSECOMPLETED NUMERIC NULL
	,EMP_ID INT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,COURSE_ID INT NULL FOREIGN KEY REFERENCES TBL_COURSE(COURSE_ID)
)

GO

CREATE TABLE TBL_EVALUATED(
	EVALUATED_ID INT IDENTITY(1,1) PRIMARY KEY
	,EVALUATED_DATE DATETIME NULL
	,EVALUATED_RESULT NVARCHAR(500) NULL
	,EMP_C_E_ID INT NULL FOREIGN KEY REFERENCES TBL_EMPLOYEE_COURSE_ENROLMENT(EMP_C_E_ID)
)

GO

CREATE TABLE TBL_T_COMPENSATION (
	COMP_ID INT IDENTITY CONSTRAINT PK_COMPENSATION PRIMARY KEY NOT NULL
	,COMP_TYPE_ID INT FOREIGN KEY REFERENCES TBL_COMPENSATION_TYPE(COMP_TYPE_ID)
	,EMP_INFO_ID INT FOREIGN KEY REFERENCES TBL_EMPLOYEE(EMP_ID)
	,COMPDATE DATE NOT NULL
)

GO
	
CREATE TABLE TBL_DED_TRANSACT
( DED_TRANS_ID INT IDENTITY(1,1) NOT NULL,
  DED_TRANS_DESC VARCHAR(100) NOT NULL,
  DED_AMOUNT FLOAT NOT NULL,

  CONSTRAINT PK_TBL_DED_TRANSACT1 PRIMARY KEY(DED_TRANS_ID),
)
GO

CREATE TABLE TBL_GSIS
(
  GSIS_ID INT IDENTITY(1,1) NOT NULL,
  GSIS_EMPLOYEE_SHARE FLOAT NOT NULL,
  GSIS_EMPLOYER_SHARE FLOAT NOT NULL

  PRIMARY KEY(GSIS_ID)
)
GO


CREATE TABLE TBL_PAGIBIG
( PGIBG_ID INT IDENTITY(1,1) NOT NULL,
  SALARY_BASE_BELOW FLOAT NOT NULL,
  BELOW_EMPLOYEE_SHARE FLOAT NOT NULL,
  BELOW_EMPLOYER_SHARE FLOAT NOT NULL,
  SALARY_BASE_ABOVE FLOAT NOT NULL,
  ABOVE_EMPLOYEE_SHARE FLOAT NOT NULL,
  ABOVE_EMPLOYER_SHARE FLOAT NOT NULL

  CONSTRAINT PK_TBL_PAGIBIG PRIMARY KEY(PGIBG_ID)
)
GO
CREATE TABLE TBL_PHILHEALTH
( PHIL_ID INT IDENTITY(1,1) NOT NULL,
  PHIL_BRACKET INT NOT NULL,
  PHIL_RANGE_FROM FLOAT NOT NULL,
  PHIL_RANGE_TO FLOAT NOT NULL,
  PHIL_EE FLOAT NOT NULL,
  PHIL_ER FLOAT NOT NULL

  CONSTRAINT PK_TBL_PHILHEALTH PRIMARY KEY(PHIL_ID)
)
GO
CREATE TABLE TBL_WITHHELD
( WTAX_ID INT IDENTITY(1,1) NOT NULL,
  EMP_ID INT NOT NULL,
  COMP_FR FLOAT NOT NULL,
  COMP_TO FLOAT NOT NULL,
  TAX_DEP FLOAT NOT NULL,
  TAX_OVER FLOAT NOT NULL,
  TAX_EXEMP FLOAT NOT NULL,

  CONSTRAINT PK_TBL_WITHHELD PRIMARY KEY(WTAX_ID),
  CONSTRAINT FK_TBL_WITHHELD1 FOREIGN KEY(EMP_ID)
  REFERENCES TBL_EMPLOYEE(EMP_ID)
)
GO
CREATE TABLE TBL_OTHER
( OTHER_ID INT IDENTITY(1,1) NOT NULL,
  OTHER_DESC VARCHAR(100) NOT NULL,
  AMOUNT FLOAT NOT NULL,
  EMP_ID INT NOT NULL,

  CONSTRAINT PK_TBL_OTHER1 PRIMARY KEY(OTHER_ID),
   CONSTRAINT FK_TBL_OTHER FOREIGN KEY(EMP_ID)
  REFERENCES TBL_EMPLOYEE(EMP_ID)
)
GO

CREATE TABLE TBL_DEDUCTION
( DEDUCTION_ID INT IDENTITY(1,1) NOT NULL,
  EMP_ID INT NOT NULL,
  DED_TRANS_ID INT NOT NULL,
  PERIOD_START DATE NOT NULL,
  PERIOD_END DATE NOT NULL,
  GSIS_ID INT NOT NULL,
  PGIBG_ID INT NOT NULL,
  PHIL_ID INT NOT NULL,
  WTAX_ID INT NOT NULL,
  OTHER_ID INT NOT NULL,
  GROSS_DED FLOAT NOT NULL,

  PRIMARY KEY(DEDUCTION_ID),
  FOREIGN KEY(EMP_ID)
  REFERENCES TBL_EMPLOYEE(EMP_ID),
  FOREIGN KEY(GSIS_ID)
  REFERENCES TBL_GSIS(GSIS_ID),
  FOREIGN KEY(PGIBG_ID)
  REFERENCES TBL_PAGIBIG(PGIBG_ID),
  FOREIGN KEY(PHIL_ID)
  REFERENCES TBL_PHILHEALTH(PHIL_ID),
  FOREIGN KEY(WTAX_ID)
  REFERENCES TBL_WITHHELD(WTAX_ID),
  FOREIGN KEY(OTHER_ID)
  REFERENCES TBL_OTHER(OTHER_ID),
  FOREIGN KEY(DED_TRANS_ID)
  REFERENCES TBL_DED_TRANSACT(DED_TRANS_ID),
)

GO


CREATE TABLE TBL_T_PAYROLL
( 
  PAYROLL_ID INT IDENTITY(1,1) NOT NULL,
  EMP_ID INT NOT NULL,
  PR_START DATE NOT NULL,
  PR_END DATE NOT NULL,
  PAY_GRADE_ID INT NOT NULL,
  ALLOWANCE_ID INT NOT NULL,
  DEDUCTION_ID INT NOT NULL,
  GROSS_PAY FLOAT NOT NULL,
  NET_PAY FLOAT NOT NULL,

  PRIMARY KEY(PAYROLL_ID),
  FOREIGN KEY(DEDUCTION_ID)
  REFERENCES TBL_DEDUCTION(DEDUCTION_ID),
  FOREIGN KEY(EMP_ID)
  REFERENCES TBL_EMPLOYEE(EMP_ID),
  FOREIGN KEY(PAY_GRADE_ID)
  REFERENCES TBL_PAY_GRADE(PAY_GRADE_ID),
  )
  GO










--DROP TABLE TBL_DEPARTMENT

--DROP TABLE REF_EMPLOYEE_JOB

--DROP TABLE TBL_PAY_GRADE

--DROP TABLE TBL_SALARY_TYPE

--DROP TABLE TBL_EMPLOYEE

--DROP TABLE TBL_EMPLOYEE

--DROP TABLE TBL_EMPLOYEE

--DROP TABLE TBL_JOB

--DROP TABLE TBL_APPLICANT

--DROP TABLE TBL_APPLICANT_INFO

--DROP TABLE TBL_REQUIREMENT

--DROP TABLE TBL_REQUIREMENT_SET

--DROP TABLE TBL_REQUIREMENT_SET

--DROP TABLE REF_REQUIREMENT_SET

--DROP TABLE TBL_JOB_POST

--DROP TABLE REF_REQUIREMENT_SET

--DROP TABLE REF_DEPARTMENT_EMPLOYEE

--DROP TABLE REF_DEPARTMENT_MANAGER

--DROP TABLE TBL_EXAMINATION

--DROP TABLE TBL_APPLICANT_EVALUATION

--DROP TABLE TBL_INTERVIEW

--DROP TABLE REF_EMPLOYEE_EXAMINATION

--DROP TABLE TBL_PERFORMANCE_EVALUATION